version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  aws-cli:
    executor:
      name: aws-cli/default
      python-version: "3.7"
    steps:
      - checkout
      - aws-cli/install
      - run: which aws
      - run: aws --version

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli
